In [5]:
import torch
from datasets import load_dataset
import numpy as np

In [22]:
t = torch.randint(low=0, high=2, size=(20,3))
t

tensor([[1, 1, 1],
        [1, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [0, 0, 1],
        [1, 0, 1],
        [1, 1, 0],
        [1, 0, 1],
        [0, 0, 0],
        [1, 1, 1],
        [1, 0, 0],
        [1, 1, 0],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 1],
        [1, 0, 0],
        [1, 0, 1]])

In [23]:
np.unique(t, axis=0, return_inverse=True)

(array([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]]),
 array([7, 6, 3, 4, 1, 5, 6, 5, 0, 7, 4, 6, 7, 0, 7, 1, 2, 5, 4, 5]))

In [14]:
jsonl_path = '/Users/jayceping/Desktop/T2IS_data_summary.jsonl'
raw_dataset = load_dataset("json", data_files=jsonl_path, split="train")

In [12]:
raw_dataset[0]['prompt']

"THREE-PANEL Images with a 1x3 grid layout depicting a professional barber in a stylish barbershop environment.All images share a modern, lively barbershop setting with retro-inspired decor, neon accents, and checkered flooring. The barber wears a crisp black apron and has a confident demeanor, maintaining consistency in appearance and environment across scenes. [LEFT]:A barber skillfully using electric clippers to shape a client's fade haircut. The client sits in a vintage leather chair facing a large mirror reflecting hanging pendant lights. Hair strands float mid-air, captured in dynamic motion with precise tool handling. [MIDDLE]:The barber carefully trims a beard using silver scissors, leaning close to the client's face with focused precision. A neatly organized tool tray holds combs and oils, while a neon 'OPEN' sign glows warmly in the background window. [RIGHT]:The barber sweeps hair clippings into a dustpan near a polished workstation. Clean towels hang neatly on racks as sunl

In [20]:
import math
batch_size = 4
group_size = 10                # Number of repetitions per sample
unique_sample_num = 19                    # `Least` number of unique sample per epoch
num_replicas = 6      # Total number of replicas, process num, gpu num
rank = 0              # Current replica rank
seed = 42              # Random seed for synchronization

# Compute the number of samples for each batch iteration
sample_num_per_iteration = num_replicas * batch_size
step = sample_num_per_iteration // math.gcd(group_size, sample_num_per_iteration)
new_m = (unique_sample_num + step - 1) // step * step  # Round up m to be multiple of step
if new_m != unique_sample_num:
    print(f"Adjusted m from {unique_sample_num} to {new_m} to make sure `unique_sample_num`*`group_size` is multiple of `batch_size`*`num_replicas` for even distribution.")
    unique_sample_num = new_m

num_batches_per_epoch = (unique_sample_num * group_size) // sample_num_per_iteration
num_batches_per_epoch

Adjusted m from 19 to 24 to make sure `unique_sample_num`*`group_size` is multiple of `batch_size`*`num_replicas` for even distribution.


10

In [22]:
unique_sample_num, group_size, batch_size, num_replicas, unique_sample_num * group_size / (batch_size * num_replicas)

(24, 10, 4, 6, 10.0)